using Enemy;
using UnityEngine;

namespace BulletScripts
{
    public class BulletController : MonoBehaviour
    {
        public float bulletLife = 1f;
        public float damage;
        public float speed;
        private Vector3 _direction;

        private void Awake()
        {
            // Destruir la bala despu√©s de 5 segundos
            Destroy(gameObject, bulletLife);
        }

        // M√©todo para establecer la direcci√≥n de movimiento y la velocidad de la bala
        public void SetMoveDirection(Vector3 moveDirection, float bulletSpeed)
        {
            _direction = moveDirection;  // Direcci√≥n en la que se mover√° la bala
            speed = bulletSpeed;        // Velocidad de la bala
        }

        private void OnTriggerEnter(Collider other)
        {
            if (other.CompareTag("Enemy"))
            {
                EnemyController enemy = other.GetComponent<EnemyController>();
                if (enemy != null)
                {
                    enemy.TakeDamage(damage);

                    // üí• Dar puntos por impacto
                    _shooter?.AddScore(10);
                }

                Destroy(gameObject);
            }
        }

        private void Update()
        {
            // Mover la bala en la direcci√≥n establecida
            transform.Translate(_direction * (speed * Time.deltaTime), Space.World);
        }
        
        private PlayerInventory _shooter;

        public void SetShooter(PlayerInventory player)
        {
            _shooter = player;
        }
    }
}